begin;

create extension if not exists pgcrypto; 

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  phone text,
  role text not null default 'user' check (role in ('admin', 'user')),
  account_status text not null default 'active' check (account_status in ('pending', 'active', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.signup_requests (
  id integer generated by default as identity primary key,
  user_id uuid not null unique references public.profiles (id) on delete cascade,
  email text not null,
  name text not null,
  phone text not null,
  channel text not null default 'sms' check (channel in ('sms', 'email')),
  status text not null default 'pending' check (status in ('pending', 'completed', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.registration_payments (
  id integer generated by default as identity primary key,
  signup_request_id integer not null unique references public.signup_requests (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  phone text not null,
  amount double precision not null default 250,
  mpesa_code text not null unique,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create table if not exists public.tasks (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  due_date date,
  estimated_minutes integer,
  reward_amount double precision not null default 1.75,
  created_by uuid not null references public.profiles (id) on delete restrict,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.tasks
  add column if not exists reward_amount double precision;

update public.tasks
set reward_amount = 1.75
where reward_amount is null or reward_amount <= 0;

alter table public.tasks
  alter column reward_amount set default 1.75;

alter table public.tasks
  alter column reward_amount set not null;

create table if not exists public.assignments (
  id integer generated by default as identity primary key,
  task_id integer not null unique references public.tasks (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  assigned_at timestamptz not null default now(),
  state text not null default 'assigned' check (state in ('assigned', 'claimed', 'submitted', 'reviewed', 'completed'))
);

alter table public.assignments
  drop constraint if exists assignments_task_id_key;

create unique index if not exists assignments_task_user_unique_idx
  on public.assignments (task_id, user_id);

create table if not exists public.submissions (
  id integer generated by default as identity primary key,
  assignment_id integer not null unique references public.assignments (id) on delete cascade,
  text text,
  file_path text,
  submitted_at timestamptz not null default now(),
  review_status text not null default 'pending' check (review_status in ('pending', 'approved', 'rejected')),
  feedback text
);

create table if not exists public.wallets (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  balance double precision not null default 0
);

create table if not exists public.withdrawals (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  amount double precision not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

update public.profiles
set account_status = 'active'
where role = 'user'
  and account_status = 'pending';

create or replace function public.is_admin(check_user uuid default auth.uid())
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = check_user
      and role = 'admin'
      and account_status = 'active'
  );
$$;

create or replace function public.is_active_user(check_user uuid default auth.uid())
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = check_user
      and account_status in ('active', 'pending')
  );
$$;

create or replace function public.has_confirmed_payment(check_user uuid default auth.uid())
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.registration_payments rp
    where rp.user_id = check_user
      and rp.status = 'confirmed'
  );
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'phone', '')), '')
  )
  on conflict (id) do update
    set name = excluded.name,
        phone = coalesce(excluded.phone, public.profiles.phone);

  insert into public.wallets (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_auth_user();

alter table public.profiles enable row level security;
alter table public.signup_requests enable row level security;
alter table public.registration_payments enable row level security;
alter table public.tasks enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.wallets enable row level security;
alter table public.withdrawals enable row level security;

drop policy if exists "profiles_select_self" on public.profiles;
create policy "profiles_select_self"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "signup_requests_select_self" on public.signup_requests;
create policy "signup_requests_select_self"
  on public.signup_requests
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "registration_payments_select_self" on public.registration_payments;
create policy "registration_payments_select_self"
  on public.registration_payments
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "wallets_select_self" on public.wallets;
create policy "wallets_select_self"
  on public.wallets
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "withdrawals_select_self" on public.withdrawals;
create policy "withdrawals_select_self"
  on public.withdrawals
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "tasks_select_open" on public.tasks;
create policy "tasks_select_open"
  on public.tasks
  for select
  to authenticated
  using (public.is_active_user() and status = 'open');

drop policy if exists "assignments_select_self" on public.assignments;
create policy "assignments_select_self"
  on public.assignments
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "submissions_select_self" on public.submissions;
create policy "submissions_select_self"
  on public.submissions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.assignments
      where assignments.id = submissions.assignment_id
        and assignments.user_id = (select auth.uid())
    )
  );

insert into storage.buckets (id, name, public)
values ('submission-files', 'submission-files', false)
on conflict (id) do nothing;

drop policy if exists "submission_files_insert_self" on storage.objects;
create policy "submission_files_insert_self"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'submission-files'
    and ((storage.foldername(name))[1] = (select auth.uid())::text)
  );

drop policy if exists "submission_files_select_self_or_admin" on storage.objects;
create policy "submission_files_select_self_or_admin"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'submission-files'
    and (
      (storage.foldername(name))[1] = (select auth.uid())::text
      or public.is_admin()
    )
  );

drop policy if exists "submission_files_update_self_or_admin" on storage.objects;
create policy "submission_files_update_self_or_admin"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'submission-files'
    and (
      (storage.foldername(name))[1] = (select auth.uid())::text
      or public.is_admin()
    )
  )
  with check (
    bucket_id = 'submission-files'
    and (
      (storage.foldername(name))[1] = (select auth.uid())::text
      or public.is_admin()
    )
  );

drop policy if exists "submission_files_delete_self_or_admin" on storage.objects;
create policy "submission_files_delete_self_or_admin"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'submission-files'
    and (
      (storage.foldername(name))[1] = (select auth.uid())::text
      or public.is_admin()
    )
  );

drop function if exists public.list_available_tasks();

create or replace function public.list_available_tasks()
returns table (
  id integer,
  title text,
  description text,
  due_date date,
  estimated_minutes integer,
  reward_amount double precision,
  status text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    t.id,
    t.title,
    t.description,
    t.due_date,
    t.estimated_minutes,
    t.reward_amount,
    t.status,
    t.created_at
  from public.tasks t
  where public.is_active_user()
    and t.status = 'open'
  order by t.created_at desc;
$$;

create or replace function public.get_my_payment_status()
returns table (
  payment_id integer,
  phone text,
  amount double precision,
  mpesa_code text,
  payment_status text,
  admin_note text,
  submitted_at timestamptz,
  confirmed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    rp.id as payment_id,
    rp.phone,
    rp.amount,
    rp.mpesa_code,
    rp.status as payment_status,
    rp.admin_note,
    rp.created_at as submitted_at,
    rp.confirmed_at
  from public.registration_payments rp
  where rp.user_id = (select auth.uid())
  order by rp.created_at desc
  limit 1;
$$;

create or replace function public.submit_my_registration_payment(
  p_phone text,
  p_mpesa_code text,
  p_amount double precision default 250,
  p_channel text default 'sms'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid;
  current_name text;
  current_email text;
  next_signup_request_id integer;
  existing_status text;
begin
  current_user_id := (select auth.uid());

  if current_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  if trim(coalesce(p_phone, '')) = '' then
    raise exception 'Phone number is required.';
  end if;

  if length(trim(coalesce(p_mpesa_code, ''))) < 8 then
    raise exception 'M-Pesa confirmation code is too short.';
  end if;

  select p.name, u.email
  into current_name, current_email
  from public.profiles p
  join auth.users u on u.id = p.id
  where p.id = current_user_id;

  if current_name is null then
    raise exception 'Profile not found.';
  end if;

  select rp.status
  into existing_status
  from public.registration_payments rp
  where rp.user_id = current_user_id
  order by rp.created_at desc
  limit 1;

  if existing_status = 'confirmed' then
    raise exception 'Payment is already confirmed.';
  end if;

  insert into public.signup_requests (user_id, email, name, phone, channel, status)
  values (current_user_id, coalesce(current_email, ''), current_name, trim(p_phone), p_channel, 'pending')
  on conflict (user_id) do update
    set email = excluded.email,
        name = excluded.name,
        phone = excluded.phone,
        channel = excluded.channel,
        status = 'pending'
  returning id into next_signup_request_id;

  insert into public.registration_payments (signup_request_id, user_id, phone, amount, mpesa_code, status, admin_note, confirmed_at)
  values (
    next_signup_request_id,
    current_user_id,
    trim(p_phone),
    coalesce(p_amount, 250),
    upper(trim(p_mpesa_code)),
    'pending',
    null,
    null
  )
  on conflict (signup_request_id) do update
    set phone = excluded.phone,
        amount = excluded.amount,
        mpesa_code = excluded.mpesa_code,
        status = 'pending',
        admin_note = null,
        confirmed_at = null;

  update public.profiles
  set phone = trim(p_phone)
  where id = current_user_id;

  return true;
end;
$$;

drop function if exists public.list_my_tasks();

create or replace function public.list_my_tasks()
returns table (
  assignment_id integer,
  state text,
  task_id integer,
  title text,
  description text,
  due_date date,
  estimated_minutes integer,
  reward_amount double precision,
  status text,
  review_status text,
  feedback text
)
language sql
security definer
set search_path = public
as $$
  select
    a.id as assignment_id,
    a.state,
    t.id as task_id,
    t.title,
    t.description,
    t.due_date,
    t.estimated_minutes,
    t.reward_amount,
    t.status,
    s.review_status,
    s.feedback
  from public.assignments a
  join public.tasks t on t.id = a.task_id
  left join public.submissions s on s.assignment_id = a.id
  where a.user_id = (select auth.uid())
  order by a.assigned_at desc;
$$;

create or replace function public.get_my_stats()
returns table (
  claimed integer,
  approved_to_start integer,
  completed integer,
  balance double precision
)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(sum(case when a.state in ('claimed', 'assigned', 'submitted', 'reviewed', 'completed') then 1 else 0 end), 0)::integer as claimed,
    coalesce(sum(case when a.state = 'assigned' then 1 else 0 end), 0)::integer as approved_to_start,
    coalesce(sum(case when a.state = 'completed' then 1 else 0 end), 0)::integer as completed,
    coalesce(w.balance, 0) as balance
  from public.wallets w
  left join public.assignments a on a.user_id = w.user_id
  where w.user_id = (select auth.uid())
  group by w.balance;
$$;

create or replace function public.claim_task(p_task_id integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_assignment_id integer;
begin
  if not public.is_active_user() then
    raise exception 'Your account is not active yet.';
  end if;

  if not public.has_confirmed_payment() then
    raise exception 'Submit and confirm your M-Pesa payment first.';
  end if;

  if not exists (
    select 1
    from public.tasks
    where id = p_task_id
      and status = 'open'
  ) then
    raise exception 'Task not found or not open.';
  end if;

  if exists (
    select 1
    from public.assignments
    where task_id = p_task_id
      and user_id = (select auth.uid())
  ) then
    raise exception 'You already have this task in your list.';
  end if;

  insert into public.assignments (task_id, user_id, state)
  values (p_task_id, (select auth.uid()), 'claimed')
  returning id into next_assignment_id;

  return next_assignment_id;
end;
$$;

create or replace function public.request_withdrawal()
returns table (
  ok boolean,
  amount double precision
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_balance double precision;
begin
  if not public.is_active_user() then
    raise exception 'Your account is not active yet.';
  end if;

  if not public.has_confirmed_payment() then
    raise exception 'Submit and confirm your M-Pesa payment first.';
  end if;

  select balance
  into current_balance
  from public.wallets
  where user_id = (select auth.uid())
  for update;

  current_balance := coalesce(current_balance, 0);

  if current_balance < 500 then
    raise exception 'Withdraw unlocks at $500.';
  end if;

  insert into public.withdrawals (user_id, amount)
  values ((select auth.uid()), current_balance);

  update public.wallets
  set balance = 0
  where user_id = (select auth.uid());

  return query select true, current_balance;
end;
$$;

drop function if exists public.create_task(text, text, date, integer);

create or replace function public.create_task(
  p_title text,
  p_description text,
  p_due_date date default null,
  p_estimated_minutes integer default null,
  p_reward_amount double precision default 1.75
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_task_id integer;
  sanitized_reward double precision;
begin
  if not public.is_admin() then
    raise exception 'Only admins can create tasks.';
  end if;

  sanitized_reward := coalesce(p_reward_amount, 1.75);

  if sanitized_reward <= 0 then
    raise exception 'Reward amount must be greater than zero.';
  end if;

  insert into public.tasks (title, description, due_date, estimated_minutes, reward_amount, created_by)
  values (
    trim(p_title),
    trim(p_description),
    p_due_date,
    p_estimated_minutes,
    sanitized_reward,
    (select auth.uid())
  )
  returning id into next_task_id;

  return next_task_id;
end;
$$;

create or replace function public.assign_task(
  p_task_id integer,
  p_user_id uuid
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_assignment_id integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can assign tasks.';
  end if;

  if not exists (
    select 1
    from public.tasks
    where id = p_task_id
      and status = 'open'
  ) then
    raise exception 'Task not found or not open.';
  end if;

  if exists (
    select 1
    from public.assignments
    where task_id = p_task_id
      and user_id = p_user_id
  ) then
    raise exception 'That user already has this task.';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = p_user_id
      and role = 'user'
      and account_status in ('active', 'pending')
      and public.has_confirmed_payment(p_user_id)
  ) then
    raise exception 'You can only assign tasks to users with confirmed payment.';
  end if;

  insert into public.assignments (task_id, user_id, state)
  values (p_task_id, p_user_id, 'assigned')
  returning id into next_assignment_id;

  return next_assignment_id;
end;
$$;

create or replace function public.approve_assignment_start(p_assignment_id integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can approve claimed tasks.';
  end if;

  if not exists (
    select 1
    from public.assignments
    where id = p_assignment_id
      and state = 'claimed'
  ) then
    raise exception 'Assignment is not waiting for approval.';
  end if;

  update public.assignments
  set state = 'assigned'
  where id = p_assignment_id;

  return true;
end;
$$;

create or replace function public.delete_task_record(p_task_id integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can delete tasks.';
  end if;

  delete from public.tasks
  where id = p_task_id;

  if not found then
    raise exception 'Task not found.';
  end if;

  return true;
end;
$$;

create or replace function public.list_claims()
returns table (
  assignment_id integer,
  task_id integer,
  user_id uuid,
  assigned_at timestamptz,
  state text,
  task_title text,
  task_due_date date,
  user_name text,
  user_email text
)
language sql
security definer
set search_path = public
as $$
  select
    a.id as assignment_id,
    a.task_id,
    a.user_id,
    a.assigned_at,
    a.state,
    t.title as task_title,
    t.due_date as task_due_date,
    p.name as user_name,
    u.email as user_email
  from public.assignments a
  join public.tasks t on t.id = a.task_id
  join public.profiles p on p.id = a.user_id
  join auth.users u on u.id = a.user_id
  where public.is_admin()
    and a.state = 'claimed'
  order by a.assigned_at desc;
$$;

create or replace function public.list_signup_requests()
returns table (
  id integer,
  name text,
  email text,
  phone text,
  channel text,
  status text,
  created_at timestamptz,
  payment_id integer,
  amount double precision,
  mpesa_code text,
  payment_status text,
  admin_note text,
  confirmed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    sr.id,
    sr.name,
    sr.email,
    sr.phone,
    sr.channel,
    sr.status,
    sr.created_at,
    rp.id as payment_id,
    rp.amount,
    rp.mpesa_code,
    rp.status as payment_status,
    rp.admin_note,
    rp.confirmed_at
  from public.signup_requests sr
  left join public.registration_payments rp on rp.signup_request_id = sr.id
  where public.is_admin()
    and sr.status <> 'completed'
  order by sr.created_at desc;
$$;

create or replace function public.confirm_signup_payment(p_payment_id integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user_id uuid;
begin
  if not public.is_admin() then
    raise exception 'Only admins can confirm payments.';
  end if;

  select user_id
  into target_user_id
  from public.registration_payments
  where id = p_payment_id
    and status = 'pending';

  if target_user_id is null then
    raise exception 'Payment not found or already processed.';
  end if;

  update public.registration_payments
  set status = 'confirmed',
      confirmed_at = now(),
      admin_note = null
  where id = p_payment_id;

  update public.signup_requests
  set status = 'completed'
  where user_id = target_user_id;

  return true;
end;
$$;

create or replace function public.reject_signup_payment(
  p_payment_id integer,
  p_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user_id uuid;
begin
  if not public.is_admin() then
    raise exception 'Only admins can reject payments.';
  end if;

  select user_id
  into target_user_id
  from public.registration_payments
  where id = p_payment_id;

  if target_user_id is null then
    raise exception 'Payment not found.';
  end if;

  update public.registration_payments
  set status = 'rejected',
      admin_note = nullif(trim(coalesce(p_note, '')), '')
  where id = p_payment_id;

  update public.signup_requests
  set status = 'rejected'
  where user_id = target_user_id;

  return true;
end;
$$;

drop function if exists public.list_tasks_overview();

create or replace function public.list_tasks_overview()
returns table (
  id integer,
  title text,
  description text,
  due_date date,
  estimated_minutes integer,
  reward_amount double precision,
  status text,
  created_at timestamptz,
  claim_count integer,
  claimers text
)
language sql
security definer
set search_path = public
as $$
  select
    t.id,
    t.title,
    t.description,
    t.due_date,
    t.estimated_minutes,
    t.reward_amount,
    t.status,
    t.created_at,
    count(a.id)::integer as claim_count,
    coalesce(string_agg(u.email, ', ' order by u.email), '') as claimers
  from public.tasks t
  left join public.assignments a on a.task_id = t.id
  left join auth.users u on u.id = a.user_id
  where public.is_admin()
  group by t.id
  order by t.created_at desc;
$$;

drop function if exists public.list_users_overview();

create or replace function public.list_users_overview()
returns table (
  id uuid,
  name text,
  email text,
  phone text,
  account_status text,
  tasks_claimed integer,
  tasks_submitted integer,
  tasks_completed integer,
  balance double precision
)
language sql
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    u.email,
    p.phone,
    p.account_status,
    count(a.id)::integer as tasks_claimed,
    coalesce(sum(case when a.state = 'submitted' then 1 else 0 end), 0)::integer as tasks_submitted,
    coalesce(sum(case when a.state = 'completed' then 1 else 0 end), 0)::integer as tasks_completed,
    coalesce(w.balance, 0) as balance
  from public.profiles p
  join auth.users u on u.id = p.id
  left join public.assignments a on a.user_id = p.id
  left join public.wallets w on w.user_id = p.id
  where public.is_admin()
    and p.role = 'user'
  group by p.id, p.name, u.email, p.phone, p.account_status, w.balance
  order by p.created_at desc;
$$;

create or replace function public.delete_user_account(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can delete users.';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = p_user_id
      and role = 'user'
  ) then
    raise exception 'User not found.';
  end if;

  delete from auth.users
  where id = p_user_id;

  return true;
end;
$$;

create or replace function public.set_user_balance(
  p_user_id uuid,
  p_amount double precision
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can update balances.';
  end if;

  if p_amount < 0 then
    raise exception 'Amount must be zero or greater.';
  end if;

  insert into public.wallets (user_id, balance)
  values (p_user_id, p_amount)
  on conflict (user_id) do update
    set balance = excluded.balance;

  return true;
end;
$$;

create or replace function public.submit_assignment(
  p_assignment_id integer,
  p_text text default null,
  p_file_path text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid;
  current_state text;
begin
  select user_id, state
  into owner_id, current_state
  from public.assignments
  where id = p_assignment_id;

  if owner_id is null then
    raise exception 'Assignment not found.';
  end if;

  if owner_id <> (select auth.uid()) then
    raise exception 'You can only submit your own assignments.';
  end if;

  if current_state not in ('assigned', 'submitted') then
    raise exception 'This assignment is not ready for submission.';
  end if;

  insert into public.submissions (assignment_id, text, file_path, submitted_at, review_status, feedback)
  values (p_assignment_id, nullif(trim(coalesce(p_text, '')), ''), p_file_path, now(), 'pending', null)
  on conflict (assignment_id) do update
    set text = excluded.text,
        file_path = coalesce(excluded.file_path, public.submissions.file_path),
        submitted_at = now(),
        review_status = 'pending',
        feedback = null;

  update public.assignments
  set state = 'submitted'
  where id = p_assignment_id;

  return true;
end;
$$;

drop function if exists public.list_submissions(integer);

create or replace function public.list_submissions(p_task_id integer default null)
returns table (
  submission_id integer,
  text text,
  file_path text,
  submitted_at timestamptz,
  review_status text,
  feedback text,
  task_id integer,
  task_title text,
  reward_amount double precision,
  task_due_date date,
  user_id uuid,
  user_name text,
  user_email text,
  assignment_id integer,
  assignment_state text
)
language sql
security definer
set search_path = public
as $$
  select
    s.id as submission_id,
    s.text,
    s.file_path,
    s.submitted_at,
    s.review_status,
    s.feedback,
    t.id as task_id,
    t.title as task_title,
    t.reward_amount,
    t.due_date as task_due_date,
    p.id as user_id,
    p.name as user_name,
    u.email as user_email,
    a.id as assignment_id,
    a.state as assignment_state
  from public.submissions s
  join public.assignments a on a.id = s.assignment_id
  join public.tasks t on t.id = a.task_id
  join public.profiles p on p.id = a.user_id
  join auth.users u on u.id = a.user_id
  where public.is_admin()
    and (p_task_id is null or a.task_id = p_task_id)
  order by s.submitted_at desc;
$$;

create or replace function public.review_submission(
  p_submission_id integer,
  p_review_status text,
  p_feedback text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_assignment_id integer;
  target_user_id uuid;
  previous_status text;
  task_reward double precision;
begin
  if not public.is_admin() then
    raise exception 'Only admins can review submissions.';
  end if;

  if p_review_status not in ('approved', 'rejected') then
    raise exception 'Review status must be approved or rejected.';
  end if;

  select s.assignment_id, a.user_id, s.review_status, t.reward_amount
  into target_assignment_id, target_user_id, previous_status, task_reward
  from public.submissions s
  join public.assignments a on a.id = s.assignment_id
  join public.tasks t on t.id = a.task_id
  where s.id = p_submission_id
  for update;

  if target_assignment_id is null then
    raise exception 'Submission not found.';
  end if;

  if previous_status <> 'pending' then
    raise exception 'This submission has already been reviewed.';
  end if;

  update public.submissions
  set review_status = p_review_status,
      feedback = nullif(trim(coalesce(p_feedback, '')), '')
  where id = p_submission_id;

  if p_review_status = 'approved' then
    update public.assignments
    set state = 'completed'
    where id = target_assignment_id;

    insert into public.wallets (user_id, balance)
    values (target_user_id, 0)
    on conflict (user_id) do nothing;

    update public.wallets
    set balance = balance + coalesce(task_reward, 1.75)
    where user_id = target_user_id;
  else
    update public.assignments
    set state = 'assigned'
    where id = target_assignment_id;
  end if;

  return true;
end;
$$;

grant execute on function public.list_available_tasks() to authenticated;
grant execute on function public.get_my_payment_status() to authenticated;
grant execute on function public.list_my_tasks() to authenticated;
grant execute on function public.get_my_stats() to authenticated;
grant execute on function public.claim_task(integer) to authenticated;
grant execute on function public.submit_my_registration_payment(text, text, double precision, text) to authenticated;
grant execute on function public.request_withdrawal() to authenticated;
grant execute on function public.create_task(text, text, date, integer, double precision) to authenticated;
grant execute on function public.assign_task(integer, uuid) to authenticated;
grant execute on function public.approve_assignment_start(integer) to authenticated;
grant execute on function public.delete_task_record(integer) to authenticated;
grant execute on function public.list_claims() to authenticated;
grant execute on function public.list_signup_requests() to authenticated;
grant execute on function public.confirm_signup_payment(integer) to authenticated;
grant execute on function public.reject_signup_payment(integer, text) to authenticated;
grant execute on function public.list_tasks_overview() to authenticated;
grant execute on function public.list_users_overview() to authenticated;
grant execute on function public.delete_user_account(uuid) to authenticated;
grant execute on function public.set_user_balance(uuid, double precision) to authenticated;
grant execute on function public.submit_assignment(integer, text, text) to authenticated;
grant execute on function public.list_submissions(integer) to authenticated;
grant execute on function public.review_submission(integer, text, text) to authenticated;

commit;
